package org.bob.learn.dao.mapper;

import java.util.List;
import org.bob.learn.dao.model.Country;

public interface CountryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbg.generated Sat Aug 01 12:22:22 CST 2020
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbg.generated Sat Aug 01 12:22:22 CST 2020
     */
    int insert(Country record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbg.generated Sat Aug 01 12:22:22 CST 2020
     */
    Country selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbg.generated Sat Aug 01 12:22:22 CST 2020
     */
    List<Country> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbg.generated Sat Aug 01 12:22:22 CST 2020
     */
    int updateByPrimaryKey(Country record);
}