server:
  port: 8080
  undertow:
    threads:
      io: 8
      worker: 256
    accesslog:
      dir: /apprun/logs/${spring.application.name}/access
      enabled: true
      rotate: true
    buffer-size: 10240
    io-threads: 4
    worker-threads: 256
  servlet:
    context-path: /undertow
spring:
  application:
    name: learn-undertow
  redis:
    host: 127.0.0.1
    port: 6379
    password: Mm_1989321
    timeout: 5s
    password: Mm_1989321
    timeout: 5s
    cluster:
      nodes:
        - 172.28.51.59:6379
        - 172.28.51.66:6379
        - 172.28.51.186:6379
      max-redirects: 5
    lettuce:
      pool:
        min-idle: 1
        max-idle: 5
        max-active: 8
        max-wait: 2s
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/world?serverTimezone=UTC
    url: jdbc:mysql://172.28.51.59:3306/learn
    username: learn
    password: Mm_1989321
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 60000
      idle-timeout: 60000
      max-lifetime: 1800000
      minimum-idle: 5
      maximum-pool-size: 10
      pool-name: ${spring.application.name}
      dataSourceProperties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
logging:
  level:
    root: info
  file:
    total-size-cap: 10GB
    clean-history-on-start: true
    max-history: 7
    max-size: 500MB
    path: /apprun/logs/${spring.application.name}/business
management:
  server:
    port: 8888
  metrics:
    export:
      prometheus:
        enabled: true
        step: 5s
        descriptions: true
  endpoint:
    prometheus:
      enabled: true
    beans:
      enabled: true
    health:
      enabled: true
    httptrace:
      enabled: true
    info:
      enabled: true
    loggers:
      enabled: true
    metrics:
      enabled: true
    threaddump:
      enabled: true
  endpoints:
    web:
      exposure:
        include: beans,prometheus,health,httptrace,info,loggers,metrics,threaddump
